
version: '3.8' 
services:
  db:
    image: postgres:15-alpine 
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=packvote
    
    ports:
      - "5432:5432"
      
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:

